#!/usr/bin/env python
"""Lorem ipsum."""
from pathlib import Path

from git import Commit, Repo


def get_modified_components(repo_root: Path, modified_files: set[Path]) -> set[Path]:
    """Lorem ipsum."""
    components_root = repo_root / "homeassistant" / "components"
    return {
        f.relative_to(components_root).parts[0]
        for f in modified_files
        if f.is_relative_to(components_root)
    }


def _get_common_ancestor_commit(repo: Repo, base_branch: str) -> Commit:
    common_ancestor_commit = repo.merge_base(repo.refs[base_branch], repo.head)
    assert len(common_ancestor_commit) == 1
    return common_ancestor_commit[0]


def main(
    repo_root: Path = Path(__file__).parents[1], base_branch: str = "origin/dev"
) -> set[Path]:
    """Lorem ipsum."""
    repo = Repo(repo_root)
    common_ancestor_commit = _get_common_ancestor_commit(repo, base_branch)
    diffs = common_ancestor_commit.diff(None)

    modified_files = set()
    for diff in diffs:
        modified_files.add(Path(repo_root) / diff.b_path)

    for u in repo.untracked_files:
        modified_files.add(Path(repo_root) / u)

    return get_modified_components(repo_root, modified_files)


if __name__ == "__main__":
    print(main())  # noqa: T201
